quarkus.log.file.enable=TRUE
quarkus.log.file.level=DEBUG
quarkus.log.console.level=INFO
quarkus.log.level=DEBUG

#Banco de Dados H2
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:card-payment-api;INIT=RUNSCRIPT FROM 'classpath:scripts/carga-db.sql'
quarkus.datasource.jdbc.max-size=16
#quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

#TEST
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:card-payment-api;INIT=RUNSCRIPT FROM 'classpath:scripts/carga-testes-db.sql'
%test.quarkus.datasource.jdbc.max-size=16
#%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=true

#Config Swagger Documentation
quarkus.swagger-ui.always-include=true
quarkus.health.openapi.included=true
quarkus.swagger-ui.urls.default=/api-docs-json
quarkus.smallrye-openapi.path=/api-docs-json
quarkus.swagger-ui.path=/api-docs
quarkus.swagger-ui.filter=true
